version: '3.5'

services:

  #Database
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-longlb}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-qksiowc294mcmqjw}
      POSTGRES_DB: ${POSTGRES_DB:-dev_db}
      PGDATA: ./postgres
    volumes:
       - ./postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres: 